name             'hadoop-hue-hive'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures hadoop-hue-hive'
long_description 'Installs/Configures hadoop-hue-hive'
version          '0.1.0'
